#!/bin/bash

echo "generating stream"
i=1
#kick off nc sockets and add data
while [ true ];
do
    echo "while $i";
    while read -r line; sleep 1; do echo $line | awk -F $'::' -v OFS='::' '{print $1,$2,$3+$1; }'; done < ./maintenance_data.csv | nc -lk localhost 9999
    i=$((i+1));
done
