#!/bin/bash

pwd
echo "running streaming job"
#build and run spark job
mvn package; mvn package && nohup dse spark-submit --class com.datastax.powertools.analytics.SparkMLPredictiveMaintenenceServeJDBC target/StreamingMLPredictiveMaintenence-0.1.jar localhost 9999&
